export const PERMISSIONS = {
  AUTH_SESSION_MANAGE: 'auth.session.manage',
  ACADEMIC_READ: 'academic.read',
  ACADEMIC_MANAGE: 'academic.manage',
  ACADEMIC_CALENDAR_READ: 'academic-calendar.read',
  ACADEMIC_CALENDAR_MANAGE: 'academic-calendar.manage',
  SCHEDULE_READ: 'schedule.read',
  SCHEDULE_MANAGE: 'schedule.manage',
  TEACHING_PLAN_READ: 'teaching-plan.read',
  TEACHING_PLAN_MANAGE: 'teaching-plan.manage',
  TEACHING_PLAN_REVIEW: 'teaching-plan.review',
  STUDENT_GRADE_READ: 'student-grade.read',
  STUDENT_GRADE_MANAGE: 'student-grade.manage',
  STUDENT_GRADE_APPROVE: 'student-grade.approve',
  STUDENT_LEAVE_READ: 'student-leave.read',
  STUDENT_LEAVE_MANAGE: 'student-leave.manage',
  STUDENT_LEAVE_REVIEW: 'student-leave.review',
  AGENDA_READ: 'agenda.read',
  AGENDA_GENERATE: 'agenda.generate',
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_MANAGE: 'attendance.manage',
  CLASS_STATUS_READ: 'class-status.read',
  CLASS_STATUS_MANAGE: 'class-status.manage',
  NOTIFICATION_READ: 'notification.read',
  NOTIFICATION_MANAGE: 'notification.manage',
  REPORTING_READ: 'reporting.read',
  REPORTING_MANAGE: 'reporting.manage',
  AUDIT_READ: 'audit.read',
  USER_MANAGE: 'user.manage',
  SYSTEM_RECOVERY_MANAGE: 'system.recovery.manage',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
